### ISSUE TITLE
v1.0: Epic

### ISSUE THREAD

**Issue by ashes999** [ashes999/flexdragon#1]
This is a major release which captures multiple major features and workflows.  Consider this a milestone of milestones.
- [ ] Basic blog support (permalink config, posts/pages, tags, RSS, comments, etc.) with Angular support (search, RSS generation, etc.)
- [ ] Basic static website support (no posts, just pages)
- [ ] Import your Wordpress blog
- [ ] Social media: post to (Facebook, Twitter) when there's new content, "share" links, Open Graph, etc.
- [ ] Possible mailing list integration to notify people on new posts
